name: Compilar Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - bpf111

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Baixar código
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y \
            bc \
            bison \
            build-essential \
            flex \
            git \
            libelf-dev \
            libssl-dev \
            libncurses-dev \
            clang \
            llvm \
            lld \
            zip \
            unzip \
            python3 \
            rsync

      - name: Corrigir KernelSU ausente
        run: |
          mkdir -p drivers/kernelsu
          touch drivers/kernelsu/Kconfig

      - name: Gerar configuração
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          make ARCH=arm64 exynos9820-m62xx_defconfig

      - name: Configurar SELinux como Permissivo
        run: |
          # Garante que o SELinux não imponha restrições (Permissive)
          sed -i 's/CONFIG_SECURITY_SELINUX_ENFORCE=y/CONFIG_SECURITY_SELINUX_ENFORCE=n/' .config
          # Define o parâmetro de boot para não forçar o modo Enforcing
          echo "CONFIG_SECURITY_SELINUX_BOOTPARAM_VALUE=0" >> .config

      - name: Compilar Kernel
        run: |
          make -j$(nproc) \
            ARCH=arm64 \
            CC=clang \
            LLVM=1 \
            LLVM_IAS=1

      - name: Salvar Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-build
          path: |
            arch/arm64/boot/Image
            arch/arm64/boot/Image.gz
            arch/arm64/boot/Image.gz-dtb
