name: Compilar Kernel Backport

on:
  push:
    branches: [ "bpf111" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Baixar código
        uses: actions/checkout@v3
        with:
          ref: bpf111

      - name: Instalar ferramentas
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential curl flex clang lld llvm libssl-dev libncurses5-dev python3 unzip

      - name: Compilar Kernel
        run: |
          export ARCH=arm64
          export CC=clang
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          make mrproper
          cp arch/arm64/configs/beyond2lte.config .config
          
          # Desativar recursos BPF que causam erros de compilação
          sed -i 's/CONFIG_BPF=y/CONFIG_BPF=n/' .config
          sed -i 's/CONFIG_BPF_SYSCALL=y/CONFIG_BPF_SYSCALL=n/' .config
          sed -i 's/CONFIG_BPF_JIT=y/CONFIG_BPF_JIT=n/' .config
          
          # SELinux Permissivo
          sed -i 's/CONFIG_SECURITY_SELINUX_ENFORCE=y/CONFIG_SECURITY_SELINUX_ENFORCE=n/' .config
          
          make olddefconfig
          make -j$(nproc)
ll 
