name: Compilar Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - bpf111

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Baixar código
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison build-essential flex git libelf-dev libssl-dev libncurses-dev clang llvm lld zip unzip python3 rsync

      - name: Adicionar KernelSU
        run: |
          rm -rf drivers/kernelsu
          git clone --depth=1 https://github.com/tiann/KernelSU drivers/kernelsu

      - name: Gerar configuração
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          make ARCH=arm64 exynos9820-m62xx_defconfig

      - name: Configurar SELinux Permissivo
        run: |
          # Garante a desativação da imposição do SELinux
          sed -i 's/CONFIG_SECURITY_SELINUX_ENFORCE=y/CONFIG_SECURITY_SELINUX_ENFORCE=n/g' .config
          # Define o parâmetro de boot para permissivo
          echo "CONFIG_SECURITY_SELINUX_BOOTPARAM_VALUE=0" >> .config
          # Garante que o modo enforcing não seja forçado
          echo "CONFIG_SECURITY_SELINUX_DISABLE=n" >> .config

      - name: Atualizar configuração
        run: |
          make ARCH=arm64 olddefconfig

      - name: Compilar Kernel
        run: |
          make -j2 \
            ARCH=arm64 \
            CC=clang \
            LLVM=1 \
            LLVM_IAS=1 \
            V=1

      - name: Salvar Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-build
          path: |
            arch/arm64/boot/Image
            arch/arm64/boot/Image.gz
            arch/arm64/boot/Image.gz-dtb
            arch/arm64/boot/dtb
